### ISSUE TITLE
Capture Redirects as based in Firebase Documentation

### ISSUE THREAD

**Issue by tHBp** [ncruces/appengine-hosting#1]
Capture Redirects don't work as mentioned [in official firebase docs](https://firebase.google.com/docs/hosting/full-config)
`{
  "source": "/blog/:post*",
  "destination": "https://blog.myapp.com/:post*",
  "type": 301
}`

**Comment by ncruces** [comment]
I've just tested that exact redirect, seems to work.

[MCVE](https://stackoverflow.com/help/mcve) please?

**Comment by tHBp** [comment]
My bad, I was testing relevant files from this repository against [simplehttp2server](https://github.com/GoogleChromeLabs/simplehttp2server) repository and I missed out on a few blocks of code. Apologies for that, closing this issue.

**Comment by ncruces** [comment]
No problem. I haven't got round to adding capture redirects there, like I [said](https://github.com/GoogleChromeLabs/simplehttp2server/issues/36) I would.
