### ISSUE TITLE
Sites are very slow if 404 set to same as index

### ISSUE THREAD

**Issue by tags2k** [ncruces/appengine-hosting#2]
Not sure if this could be a warning upon running the app or otherwise be preventable in any way, but I accidentally had the index and 404 pages set to the same HTML file and the site would take upwards of a second to respond - when I changed the 404 page to something else it was suddenly lightning fast.

**Comment by ncruces** [comment]
Hi, can you share a bit more about your configuration?

To be clear, I'm assuming you set "main page suffix" and "not found page" in your bucket configuration to the same path?

Do you *also* have a `firebase.json` configuration file? Are you using `rewrites`?
